### ISSUE TITLE
bootstrap issue

### ISSUE THREAD

**Issue by davinder007** [manvirarethos/MEANDEV#1]
bootstrap css is no implement in  angular 2 by using bower plz help me

**Comment by manvirarethos** [comment]
Okay will give you step to implement bootstrap

**Comment by manvirarethos** [comment]
Steps
1. npm install bootstrap
This will install bootstrap package to you system now in 2 Step
2.  Add path for css  in angular-cli.json 
look like :  "styles": [  "../node_modules/bootstrap/dist/css/bootstrap.min.css"]
same way if you want to add js file for bootstarp.
3. Add js file path to angular-cli  script section
look like : "script":["../node_modules/bootstrap/dist/js/bootstarp.min.js"]

Please try and let me know does this works for you

**Comment by davinder007** [comment]
thanks sir , its work
